use classicmodels;

/*2*/
DELETE FROM payments;
SELECT * FROM payments;

/*6*/
SHOW MASTER STATUS;
SHOW BINLOG EVENTS in 'binlog.000293' LIMIT 10;

/*
'binlog.000293', '4', 'Format_desc', '1', '126', 'Server ver: 8.0.46-0ubuntu0.24.04.3, Binlog ver: 4'
'binlog.000293', '126', 'Previous_gtids', '1', '157', ''
'binlog.000293', '157', 'Anonymous_Gtid', '1', '236', 'SET @@SESSION.GTID_NEXT= \'ANONYMOUS\''
'binlog.000293', '236', 'Query', '1', '320', 'BEGIN'
'binlog.000293', '320', 'Table_map', '1', '393', 'table_id: 106 (classicmodels.payments)'
'binlog.000293', '393', 'Delete_rows', '1', '6411', 'table_id: 106 flags: STMT_END_F'
'binlog.000293', '6411', 'Xid', '1', '6442', 'COMMIT xid=604 '
'binlog.000293', '6442', 'Anonymous_Gtid', '1', '6519', 'SET @@SESSION.GTID_NEXT= \'ANONYMOUS\''
'binlog.000293', '6519', 'Query', '1', '6679', 'use `classicmodels`; DROP TABLE IF EXISTS `clienteHistorico`  generated by server '
'binlog.000293', '6679', 'Anonymous_Gtid', '1', '6756', 'SET @@SESSION.GTID_NEXT= \'ANONYMOUS\''
*/

/*7*/
use mysql;
SELECT * FROM performance_schema.error_log
ORDER BY LOGGED DESC
LIMIT 20;


SHOW TABLES FROM performance_schema LIKE '%error%';

/*
'2026-08-06 07:47:56.812180', '8', 'Warning', 'MY-013360', 'Server', 'Plugin mysql_native_password reported: \'\'mysql_native_password\' is deprecated and will be removed in a future release. Please use caching_sha2_password instead\''
'2026-08-06 07:47:56.811526', '0', 'System', 'MY-010931', 'Server', '/usr/sbin/mysqld: ready for connections. Version: \'8.0.46-0ubuntu0.24.04.3\'  socket: \'/var/run/mysqld/mysqld.sock\'  port: 3306  (Ubuntu).'
'2026-08-06 07:47:56.811458', '0', 'System', 'MY-011323', 'Server', 'X Plugin ready for connections. Bind-address: \'127.0.0.1\' port: 33060, socket: /var/run/mysqld/mysqlx.sock'
'2026-08-06 07:47:56.785362', '0', 'System', 'MY-013602', 'Server', 'Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.'
'2026-08-06 07:47:56.785333', '0', 'Warning', 'MY-010068', 'Server', 'CA certificate ca.pem is self signed.'
'2026-08-06 07:47:56.754226', '0', 'System', 'MY-010232', 'Server', 'XA crash recovery finished.'
'2026-08-06 07:47:56.746552', '0', 'System', 'MY-010229', 'Server', 'Starting XA crash recovery...'
'2026-08-06 07:47:56.595761', '1', 'System', 'MY-013577', 'InnoDB', 'InnoDB initialization has ended.'
'2026-08-06 07:47:56.311786', '1', 'System', 'MY-013576', 'InnoDB', 'InnoDB initialization has started.'
'2026-08-06 07:47:56.303193', '0', 'System', 'MY-010116', 'Server', '/usr/sbin/mysqld (mysqld 8.0.46-0ubuntu0.24.04.3) starting as process 1819'
*/
